In [1]:
### Combining two data frames (column wise)
set.seed(1)
m <- cbind(1, 1:7) 
m

[,1] [,2]
[1,] 1    1   
[2,] 1    2   
[3,] 1    3   
[4,] 1    4   
[5,] 1    5   
[6,] 1    6   
[7,] 1    7

In [2]:
m <- cbind(m, 8:14)[, c(1, 2, 3)]
m

[,1] [,2] [,3]
[1,] 1    1     8  
[2,] 1    2     9  
[3,] 1    3    10  
[4,] 1    4    11  
[5,] 1    5    12  
[6,] 1    6    13  
[7,] 1    7    14

In [3]:
d1 <- data.frame(x=1:5, y1=rnorm(5))
d2 <- data.frame(x=2:6, y2=rnorm(5))
d1

x y1        
1 1 -0.6264538
2 2  0.1836433
3 3 -0.8356286
4 4  1.5952808
5 5  0.3295078

In [4]:
d2

x y2        
1 2 -0.8204684
2 3  0.4874291
3 4  0.7383247
4 5  0.5757814
5 6 -0.3053884

In [5]:
cbind(d1,d2)

x y1         x y2        
1 1 -0.6264538 2 -0.8204684
2 2  0.1836433 3  0.4874291
3 3 -0.8356286 4  0.7383247
4 4  1.5952808 5  0.5757814
5 5  0.3295078 6 -0.3053884

In [6]:
### Combining two data frames (row wise) 
set.seed(1)
m <- rbind(1, 1:7) 
m

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    1    1    1    1    1    1   
[2,] 1    2    3    4    5    6    7

In [7]:
m <- rbind(m, 8:14)[c(1, 2, 3), ]
m

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    1     1    1    1    1    1  
[2,] 1    2     3    4    5    6    7  
[3,] 8    9    10   11   12   13   14

In [8]:
d3 <- data.frame(x=1:5, y1=rnorm(5))
d4 <- data.frame(x=6:10, y1=rnorm(5))
d3

x y1        
1 1 -0.6264538
2 2  0.1836433
3 3 -0.8356286
4 4  1.5952808
5 5  0.3295078

In [9]:
d4

x  y1        
1  6 -0.8204684
2  7  0.4874291
3  8  0.7383247
4  9  0.5757814
5 10 -0.3053884

In [10]:
rbind(d3,d4)

x  y1        
1   1 -0.6264538
2   2  0.1836433
3   3 -0.8356286
4   4  1.5952808
5   5  0.3295078
6   6 -0.8204684
7   7  0.4874291
8   8  0.7383247
9   9  0.5757814
10 10 -0.3053884