In [3]:
from pybrain.tools.shortcuts import buildNetwork

In [4]:
net = buildNetwork(1, 4, 4, 1)

In [5]:
net.activate([1])

array([-0.23768126])

In [1]:
from pybrain.datasets import SupervisedDataSet

In [6]:
ds = SupervisedDataSet(1, 1)

In [7]:
import numpy as np

In [8]:
s = np.random.uniform(size=50)

In [9]:
trainingoutput = np.array(10*s)

In [10]:
traininginput = trainingoutput*trainingoutput

In [11]:
trainingdata = np.array([traininginput,trainingoutput])

In [12]:
trainingdata = trainingdata.T

In [13]:
from pybrain.supervised.trainers import BackpropTrainer

In [14]:
for i in range(50):
    ds.addSample((trainingdata[i,0]), (trainingdata[i,1]))

In [15]:
len(ds)

50

In [16]:
trainer = BackpropTrainer(net, ds)

In [17]:
trainer.train()

8.7750410361564306

In [18]:
trainer.trainUntilConvergence()

([4.7427327914527782,
  3.9183905867264204,
  3.5762270449407261,
  3.3241451929076562,
  3.1104820154819204,
  2.8348131879474101,
  2.5603947221643404,
  2.3980356363858277,
  2.18113217260127,
  1.9493992202349171,
  2.797597069474083,
  1.9673655134102095,
  1.9591657924498087,
  2.0895066060512768,
  2.3405977924884795,
  1.8087451452982997,
  1.5424711916241045,
  1.67712171098567,
  2.0204889203930119,
  1.5957390967575811,
  1.51360796456892,
  2.41191804892591,
  1.1443769198353595,
  1.8537288867893988,
  2.2339218905389679,
  1.3348874696622837,
  1.0654329945730294],
 [4.2826314290675658,
  3.2017100707877764,
  2.8967908867901326,
  2.6905427987376216,
  2.5109697255632351,
  2.2650484968957274,
  2.0047995323920373,
  2.0339922418492256,
  1.4755284699729456,
  1.3476058778482254,
  2.8926333268958535,
  1.2399384846887789,
  1.704190791200642,
  1.7886281377711817,
  1.8412786439427362,
  1.5979867061014399,
  1.6294421330750315,
  0.57774148608173137,
  1.87377278999457

In [20]:
print(net)

FeedForwardNetwork-11
   Modules:
    [<BiasUnit 'bias'>, <LinearLayer 'in'>, <SigmoidLayer 'hidden0'>, <SigmoidLayer 'hidden1'>, <LinearLayer 'out'>]
   Connections:
    [<FullConnection 'FullConnection-10': 'in' -> 'hidden0'>, <FullConnection 'FullConnection-5': 'hidden1' -> 'out'>, <FullConnection 'FullConnection-6': 'hidden0' -> 'hidden1'>, <FullConnection 'FullConnection-7': 'bias' -> 'out'>, <FullConnection 'FullConnection-8': 'bias' -> 'hidden0'>, <FullConnection 'FullConnection-9': 'bias' -> 'hidden1'>]



In [21]:
net.activate([1])

array([ 1.42583762])

In [22]:
net.activate([4])

array([ 2.45441624])

In [23]:
net.activate([9])

array([ 3.20545857])

In [24]:
net.activate([16])

array([ 4.31358064])

In [25]:
net.activate([25])

array([ 5.89741786])